version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  
  kafka1:
    image: confluentinc/cp-kafka:latest
    restart: always
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: HOST_LISTENER://0.0.0.0:9092, INT_LISTENER://0.0.0.0:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: HOST_LISTENER:PLAINTEXT, INT_LISTENER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: HOST_LISTENER://localhost:9092, INT_LISTENER://kafka1:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: INT_LISTENER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
  
  kafka2:
    image: confluentinc/cp-kafka:latest
    restart: always
    depends_on:
      - zookeeper
    ports:
      - 9093:9092
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: HOST_LISTENER://0.0.0.0:9092, INT_LISTENER://0.0.0.0:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: HOST_LISTENER:PLAINTEXT, INT_LISTENER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: HOST_LISTENER://localhost:9093, INT_LISTENER://kafka2:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: INT_LISTENER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2

  kafdrop:
    image: obsidiandynamics/kafdrop
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka1:29092"
    depends_on:
      - zookeeper
      - kafka1
      - kafka2

  redis:
    image: redis:latest
    restart: always
    ports:
      - 6380:6379
    command: redis-server --appendonly yes --requirepass 1234

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: your_database
      MYSQL_USER: your_username
      MYSQL_PASSWORD: your_password
    ports:
      - "3307:3306"

  cassandra:
    image: cassandra:latest
    restart: always
    ports:
      - "9042:9042"  # Cassandra native transport port
      - "7000:7000"  # Cassandra inter-node communication port
      - "7001:7001"  # Cassandra SSL inter-node communication port
      - "7199:7199"  # Cassandra JMX monitoring port
      - "9160:9160"  # Cassandra Thrift client port
    environment:
      - CASSANDRA_CLUSTER_NAME=MyCassandraCluster  # Change as per your preference
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch  # Change if needed
      - MAX_HEAP_SIZE=512M  # Adjust according to your system resources
      - HEAP_NEWSIZE=100M  # Adjust according to your system resources

  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"